### ISSUE TITLE
udpipe2: UD syntactic relations names (ParCzech vs ParlaMint)

### ISSUE THREAD

**Issue by matyaskopp** [ufal/ParCzech#41]
Original [extended syntactic relations](https://universaldependencies.org/ext-dep-index.html) in Universal Dependencies use a colon `:` in names but ParlaMint project uses underscore `_`.

https://github.com/clarin-eric/ParlaMint/issues/5#issuecomment-746654797

**Comment by TomazErjavec** [comment]
You are right, I will change back to colon.

**Comment by TomazErjavec** [comment]
As discussed in clarin-eric/ParlaMint#27, I'm afraid I won't, after all. Blame it on the silly definition of xsl:ID please!

**Comment by matyaskopp** [comment]
mentioned here: https://github.com/clarin-eric/ParlaMint/issues/43
